language: c

before_install:
  - sudo apt-get -y install libjson-c-dev
  - sudo apt-get -y install cmake

compiler:
  - gcc

script: 
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir bin
  - cd bin
  - cmake ..
  - make